export type PresetKey = keyof typeof PRESET_ITEMS;

const PRESETS: { key: PresetKey; label: string; emoji: string }[] = [
  { key: "names", label: "List of names", emoji: "👥" },
  { key: "date", label: "Ideas for date night", emoji: "✨" },
  { key: "movie", label: "Movie night", emoji: "🎬" },
  { key: "bottle", label: "Spin the bottle", emoji: "🍾" },
  { key: "truth", label: "Truth or dare", emoji: "🎯" },
  { key: "dinner", label: "What’s For Dinner", emoji: "🍽️" },
  { key: "workout", label: "Workout Program", emoji: "🏋️" },
  { key: "team", label: "Team Building Games", emoji: "🤝" },
  { key: "chorus", label: "Chores Wheel", emoji: "🎼" },
];

const PRESET_ITEMS = {
  names: [
    "Alex",
    "Taylor",
    "Jordan",
    "Riley",
    "Morgan",
    "Casey",
    "Sam",
    "Jamie",
  ],
  date: [
    "Picnic at sunset",
    "Karaoke duet",
    "Pasta cook-off",
    "Museum stroll",
    "Dessert crawl",
    "Game night",
    "Movie + takeout",
    "Stargazing",
  ],
  movie: [
    "Comedy",
    "Thriller",
    "Animated",
    "Documentary",
    "Rom-com",
    "Action",
    "Indie",
    "Family",
  ],
  bottle: [
    "High-five",
    "Tell a joke",
    "Compliment someone",
    "Act like a cat",
    "Group selfie",
    "Dance 10s",
    "Fun fact",
    "Free pass",
  ],
  truth: [
    "Hidden talent?",
    "Instant happy?",
    "Most used emoji?",
    "Guilty-pleasure show?",
    "First crush?",
    "Biggest fear?",
    "Bad habit?",
    "Best tip?",
  ],
  dinner: [
    "Tacos",
    "Stir-fry",
    "Pasta",
    "Pizza",
    "Burgers",
    "Salmon",
    "Curry",
    "Buddha bowl",
  ],
  workout: [
    "Full-body",
    "Upper body",
    "Lower body",
    "Core",
    "Yoga",
    "HIIT",
    "Run",
    "Cycle",
  ],
  team: [
    "Two truths & a lie",
    "Show & tell",
    "Emoji icebreaker",
    "Compliment circle",
    "Brainstorm",
    "Trivia",
    "Sketch & guess",
    "Mini retro",
  ],
  chorus: [
    "Soprano",
    "Alto",
    "Tenor",
    "Bass",
    "Warm-ups",
    "Breathing",
    "Dynamics",
    "Harmony",
  ],
} as const;

export { PRESETS, PRESET_ITEMS };
